FROM golang:1.25.5-alpine3.22 AS build

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -o /out/hopty-spike ./test/spike/cmd

FROM mcr.microsoft.com/playwright:v1.61.1-noble AS test

WORKDIR /work
COPY test/spike/package.json test/spike/package-lock.json ./
RUN npm ci --ignore-scripts
COPY test/spike/ ./
COPY --from=build /out/hopty-spike /usr/local/bin/hopty-spike
RUN npm test
