FROM golang:1.25.5-alpine3.22 AS base

WORKDIR /src

COPY go.mod ./
RUN go mod download

COPY . .

FROM base AS test
RUN go vet ./... && go test ./... && sh -n install/install.sh

FROM base AS build
ARG VERSION=dev
ARG GOARCH=amd64
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${GOARCH} go build -trimpath -ldflags="-s -w -X main.version=${VERSION}" -o /out/hopty ./cmd/hopty

FROM scratch AS artifact
COPY --from=build /out/hopty /hopty

FROM base AS dev
CMD ["sh"]
